--- @meta Error

--- @class (exact) yazi.Error
---
--- Properties:
--- @field code integer?
---
--- MetaMethods:
--- @metamethod __tostring()
--- @metamethod __concat(string)
---
--- @see https://yazi-rs.github.io/docs/plugins/types#shared.error
