--- @meta fs

--- @class yazi.fs.Files
--- @field [number] yazi.fs.File
---
--- MetaMethods:
--- @metamethod __len()
--- @metamethod __index(idx) Access the fs::File by index
---
--- @see https://yazi-rs.github.io/docs/plugins/types#app-data.fs-files

--- @class (exact) yazi.fs.File: yazi.File
---
--- Methods:
--- @field size fun(self: self):integer? The size of this file in bytes, or nil if its a directory and it has not been evaluated
--- @field mime fun(self: self):string? The mime-type of this file, or nil if it's a directory or hasn't been lazily calculated at all
--- @field prefix fun(self: self):string The prefix of this file relative to CWD, which used in the flat view during search.
---   For instance, if CWD is /foo, and the file is /foo/bar/baz, then the prefix is bar/
--- @field icon fun(self: self):yazi.Icon? The Icon of this file, [icon] rules are applied; if no rule matches, returns nil
--- @field style fun(self: self):yazi.ui.Style? The Style of this file, [filetype] rules are applied; if no rule matches, returns nil
--- @field is_hovered fun(self: self):boolean Whether this file is hovered
--- @field is_yanked fun(self: self):boolean Whether this file is yanked
--- @field is_selected fun(self: self):boolean Whether this file is selected
---
--- @field found fun(self: self):[integer, number]? When users find a file using the find command, the status of the file
---   nil - if it doesn't match the user's find keyword
---   {idx, all} - where idx is the position of matched file, and all represents the number of all matched files
---  TODO: Waiting for yazi document
---
--- @see https://yazi-rs.github.io/docs/plugins/types#app-data.fs-file
